import {useEffect,useRef,useState} from 'react';
import {Activity,ArrowDownToLine,ArrowRight,ArrowUpRight,BookOpen,Check,CheckCircle2,ChevronRight,Clock3,Database,ExternalLink,FileSearch,FileText,FolderOpen,GitCompareArrows,History,Layers3,LoaderCircle,Plus,Search,Settings2,ShieldCheck,SlidersHorizontal,Sparkles,Square,Upload,X,AlertCircle,Command,MessageSquare,Trash2} from 'lucide-react';

import AgentChat from './AgentChat';
import HistoryTrash from './HistoryTrash';
import CompanySearch from './CompanySearch';
import ConnectionSettings from './ConnectionSettings';
import ValuationLab from './ValuationLab';
import MemoView from './MemoView';
import './agent.css';

type Run=any;
const labels:any={chat:'研究对话',overview:'公司研究',model:'估值建模',audit:'数据核验',history:'研究版本',library:'资料库',settings:'连接设置',trash:'回收站'};
const metricIds=['revenue','n_income_attr_p','n_cashflow_act'];
const factStatus:any={verified:'双源一致',document_only:'披露文件',api_only:'接口来源',conflict:'来源冲突'};
const metricNames=['营业收入','归母净利润','经营现金流净额'];
const money=(v:any)=>v==null?'—':(Number(v)/1e8).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const rate=(v:any)=>v==null?'不适用':(Number(v)>0?'+':'')+Number(v).toFixed(2)+'%';
const changeText=(c:any)=>c?.value!=null?rate(c.value):c?.change!=null?(Number(c.change)>0?'+':'')+money(c.change)+' 亿元':'待核实';
const changeTone=(c:any)=>c?.value==null?'neutral':Number(c.value)<0?'negative':Number(c.value)>0?'positive':'neutral';
const when=(v:string)=>v?new Date(v).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'';
const status=(r:Run)=>({queued:'等待开始',running:'研究进行中',completed_with_gaps:'底稿已完成 · 有待核实项',blocked:'需要补充',failed:'执行失败',cancelled:'已取消'}[r?.state]||'尚未研究');
async function api(path:string,options:any={}) {
  const response=await fetch('/api'+path,{...options,headers:options.body instanceof FormData?{}:{'Content-Type':'application/json',...options.headers}});
  if(!response.ok) {const e=await response.json().catch(()=>({detail:'请求失败'})); throw new Error(typeof e.detail==='string'?e.detail:e.detail?.map((x:any)=>x.msg).join('；')||'请求失败');}
  return response.json();
}
const post=(path:string,body:any={})=>api(path,{method:'POST',body:JSON.stringify(body)});
function Badge({children,tone='neutral'}:any){return <span className={'badge '+tone}>{children}</span>}
function Modal({title,children,onClose,wide=false}:any) {
  useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',f);return()=>document.removeEventListener('keydown',f)},[onClose]);
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={'modal '+(wide?'wide':'')} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="关闭"><X size={20}/></button></header>{children}</section></div>
}

export default function App(){
  const [tab,setTab]=useState('chat'),[runs,setRuns]=useState<any[]>([]),[run,setRun]=useState<Run>(null),[config,setConfig]=useState<any>({}),[docs,setDocs]=useState<any[]>([]);
  const [chatPrompt,setChatPrompt]=useState('');
  const [selected,setSelected]=useState('revenue-2025'),[sourceId,setSourceId]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [showNew,setShowNew]=useState(false),[showExport,setShowExport]=useState(false),[page,setPage]=useState<any>(null);
  const [showEvidence,setShowEvidence]=useState(false);
  const [creating,setCreating]=useState(false),[loading,setLoading]=useState(true);
  const [form,setForm]=useState<any>({ticker:'000333.SZ',year:2025,as_of:new Date().toLocaleDateString('en-CA'),question:'收入和利润增长能否获得现金流支持？哪些问题值得进一步研究？',mode:'live',use_model:true,document_id:'',data_source:'default'});
  const [reviewText,setReviewText]=useState(''),[review,setReview]=useState<any>(null);
  const [comparison,setComparison]=useState<any>(null),[compareId,setCompareId]=useState('');
  const [uploadMeta,setUploadMeta]=useState({ticker:'000333.SZ',year:2025,announced_date:'2026-03-31'}),[uploading,setUploading]=useState(false);
  const fileInput=useRef<HTMLInputElement>(null);
  const busy=run&&['queued','running'].includes(run.state);
  const year=run?.request.year||2025;
  const facts=run?.facts||[],memo=run?.memo;
  const fact=facts.find((f:any)=>f.id===selected)||facts[0];
  const sources=(fact?.evidence_ids||[]).map((id:string)=>run?.evidence.find((e:any)=>e.id===id)).filter(Boolean);
  const source=sources.find((s:any)=>s.id===sourceId)||sources[0];
  const calculation=run?.calculations.find((c:any)=>c.metric===fact?.metric);
  const refreshRuns=()=>api('/runs').then(setRuns);
  async function removeRun(id:string){setError('');try{await api('/runs/'+id,{method:'DELETE'});const rows=await api('/runs');setRuns(rows);if(run?.id===id){setRun(null);localStorage.removeItem('research-run');if(rows.length)await selectRun(rows[0].id);else setTab('trash')}setNotice('研究及关联对话已移入回收站，可恢复；PDF 资料保留。')}catch(e:any){setError(e.message)}}
  async function attachExisting(d:any){setError('');try{if(!run)throw new Error('请先选择一份匹配的公司研究');const rows=await api('/conversations?run_id='+run.id);const saved=localStorage.getItem('research-conversation:'+run.id);const c=rows.find((r:any)=>r.id===saved)||rows[0]||await post('/conversations',{run_id:run.id});await post('/conversations/'+c.id+'/documents/'+d.id);localStorage.setItem('research-conversation:'+run.id,c.id);await selectRun(run.id);setTab('chat');setNotice('材料已接入当前对话，可以直接提问。')}catch(e:any){setError(e.message)}}
  useEffect(()=>{if(tab==='library')api('/documents').then(setDocs).catch(e=>setError(e.message))},[tab]);
  useEffect(()=>{if(run)setUploadMeta({ticker:run.request.ticker,year:run.request.year,announced_date:''})},[run?.id]);
  async function selectRun(id:string){setError('');try{const r=await api('/runs/'+id);setRun(r);setSelected('revenue-'+r.request.year);setSourceId('');setShowEvidence(false);setComparison(null);setCompareId('');setReview(null);localStorage.setItem('research-run',id)}catch(e:any){setError(e.message)}}
  useEffect(()=>{Promise.all([api('/settings'),api('/runs'),api('/documents')]).then(([s,r,d])=>{setConfig(s);setRuns(r);setDocs(d);setForm((f:any)=>({...f,as_of:s.today}));const saved=localStorage.getItem('research-run');if(r.length)selectRun(r.find((x:any)=>x.id===saved)?.id||r[0].id)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
  useEffect(()=>{if(!run||!busy)return;const events=new EventSource('/api/runs/'+run.id+'/events');events.onmessage=e=>{const r=JSON.parse(e.data);setRun(r);if(!['queued','running'].includes(r.state)){events.close();refreshRuns()}};events.onerror=()=>{events.close();api('/runs/'+run.id).then(setRun).catch(()=>setError('研究状态连接中断，请刷新页面查看已保存的进度'))};return()=>events.close()},[run?.id,busy]);
  useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(id)},[notice]);
  function chooseFact(id:string){setSelected(id);setSourceId('');setShowEvidence(true)}
  function discuss(text:string){setChatPrompt(text);setTab('chat')}
  async function updated(id:string){await selectRun(id);await refreshRuns()}
  async function start(data=form){setCreating(true);setError('');try{const r=await post('/runs',{...data,year:Number(data.year),document_id:data.document_id||null});setShowNew(false);await selectRun(r.id);await refreshRuns();setTab('overview')}catch(e:any){setError(e.message)}finally{setCreating(false)}}
  async function act(path:string){setError('');try{const r=await post(path);if(r.id)await selectRun(r.id);else if(run)await selectRun(run.id);await refreshRuns()}catch(e:any){setError(e.message)}}
  async function checkText(){setError('');try{setReview(await post('/runs/'+run.id+'/review',{text:reviewText}))}catch(e:any){setError(e.message)}}
  async function upload(file:File){setUploading(true);setError('');try{const data=new FormData();data.append('file',file);Object.entries(uploadMeta).forEach(([k,v])=>data.append(k,String(v)));const doc=await api('/documents',{method:'POST',body:data});setDocs(await api('/documents'));setForm((f:any)=>({...f,document_id:doc.id,ticker:doc.ticker,year:doc.year}));setNotice('材料已保存，可在新研究中选择使用')}catch(e:any){setError(e.message)}finally{setUploading(false);if(fileInput.current)fileInput.current.value=''}}

  return <div className="app-shell">
    <aside className="sidebar">
      <button className="brand" aria-label="研序首页" onClick={()=>setTab('chat')}><span className="brand-mark"><Layers3 size={23}/></span><span>研序</span><span className="brand-version" title="当前运行的应用版本">{config.version?'v'+config.version:''}</span></button>
      <button className="new-research" aria-label="新建研究" onClick={()=>setShowNew(true)}><Plus size={17}/><span>新建研究</span></button>
      <nav aria-label="研究导航">{[[MessageSquare,'chat'],[BookOpen,'overview'],[SlidersHorizontal,'model'],[ShieldCheck,'audit'],[History,'history']].map(([Icon,id]:any)=><button key={id} aria-label={labels[id]} title={labels[id]} aria-current={tab===id?'page':undefined} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={18}/><span>{labels[id]}</span></button>)}</nav>
      <nav className="secondary-nav" aria-label="资料与设置">{[[FolderOpen,'library'],[Settings2,'settings'],[Trash2,'trash']].map(([Icon,id]:any)=><button key={id} aria-label={labels[id]} title={labels[id]} aria-current={tab===id?'page':undefined} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={18}/><span>{labels[id]}</span></button>)}</nav>
      <div className="recent-heading"><span>最近研究</span><span>{runs.length}</span></div>
      <div className="recent-list">{runs.slice(0,5).map(r=><button key={r.id} className={run?.id===r.id?'selected':''} onClick={()=>{selectRun(r.id);setTab('chat')}}><span className={'tiny-dot '+(r.state==='running'?'pulse':'')}/><span>{r.company}<small>{r.request.year} · {r.request.ticker}{r.request.mode==='sample'?' · 样例':''}</small></span></button>)}</div>
      <div className="sidebar-bottom"><span className="avatar">研</span><div>我的研究空间</div><ShieldCheck size={16}/></div>
    </aside>
    <div className="workspace">
      <header className="topbar"><div><span className="muted">研究空间</span><ChevronRight size={14}/><strong>{labels[tab]}</strong></div><div className="topbar-right"><button onClick={()=>setTab('settings')} className="connection"><i className={config.model_configured?'green-dot':'gray-dot'}/> {config.model||'配置连接'}</button></div></header>
      {error&&<div className="error-banner" role="alert"><AlertCircle size={17}/><span>{error}</span><button onClick={()=>setError('')} aria-label="关闭错误"><X size={16}/></button></div>}
      {notice&&<div className="toast" role="status"><CheckCircle2 size={17}/>{notice}</div>}
      {loading?<div className="welcome"><LoaderCircle className="spin"/><p>正在载入研究空间…</p></div>:<>
      {!run&& !['library','settings','chat','trash'].includes(tab)?<div className="welcome">
        <span className="eyebrow">从事实开始，形成判断</span><h1>你的下一份研究，<br/>每一个数字都有来处。</h1><p>把财务数据、原始披露和研究判断连接起来，<br/>从一份可复核的公司底稿开始。</p>
        <div className="button-row"><button className="primary" onClick={()=>setShowNew(true)}><Plus size={17}/>开始第一份研究</button><button className="secondary" disabled={creating} onClick={()=>start({...form,mode:'sample',ticker:'000333.SZ',year:2025,document_id:''})}>体验美的样例<ArrowRight size={16}/></button></div>
        <div className="welcome-features"><span><Database/>财务双源核对</span><span><FileSearch/>原始证据追溯</span><span><GitCompareArrows/>研究版本留痕</span></div>
      </div>:<>
        {!['library','settings','chat','trash'].includes(tab)&&<div className="company-heading"><div className="company-title"><span className="company-mark">{run?.request.ticker==='000333.SZ'?'MD':run?.request.ticker.slice(0,2)}</span><div><div className="title-line"><h1>{run?.company}</h1><Badge>{run?.request.ticker}</Badge><Badge tone={run?.request.mode==='sample'?'amber':'blue'}>{run?.request.mode==='sample'?'样例回放':'实时研究'}</Badge></div><p>{year} 年度财务研究 <span>·</span> 数据截止 {run?.request.as_of} <span>·</span> 合并口径</p></div></div><div className="button-row">{busy?<button className="secondary" onClick={()=>act('/runs/'+run.id+'/cancel')}><Square size={13}/>取消研究</button>:<button className="secondary" onClick={()=>{setForm({...run.request,mode:'live',as_of:config.today});setShowNew(true)}}><Sparkles size={15}/>开展实时研究</button>}<button className="secondary" aria-label="删除当前研究" disabled={busy} onClick={()=>removeRun(run.id)}><Trash2 size={15}/>删除研究</button><button className="primary" onClick={()=>setShowExport(true)} disabled={!facts.length}><ArrowDownToLine size={16}/>导出底稿</button></div></div>}
        {busy&&<div className="progress-panel"><LoaderCircle className="spin" size={18}/><div><strong>{run.events.at(-1)?.label||'准备研究'}</strong><span>{run.events.at(-1)?.detail}</span></div><b>{run.progress}%</b><div className="progress-track"><i style={{width:run.progress+'%'}}/></div></div>}
        {tab==='chat'&&<AgentChat key={run?.id||'free'} run={run} config={config} onRunUpdated={updated} onOpen={setTab} onNewResearch={()=>setShowNew(true)} prompt={chatPrompt} onPromptConsumed={()=>setChatPrompt('')}/>}
        {tab==='overview'&&run&&<div className={'research-layout '+(showEvidence?'with-evidence':'reading-view')}><main className="research-main">
          <div className="section-heading"><div><h2>财务概览</h2></div><div className="snapshot-actions"><span className="small-muted">人民币亿元</span><button className="text-link" aria-expanded={showEvidence} aria-controls="research-evidence" onClick={()=>setShowEvidence(!showEvidence)}><FileSearch size={14}/>{showEvidence?'收起来源':'查看来源'}</button></div></div>
          <div className="metric-grid">{metricIds.map((id,i)=>{const f=facts.find((f:any)=>f.metric===id&&f.year===year),p=facts.find((f:any)=>f.metric===id&&f.year===year-1),c=run.calculations.find((c:any)=>c.metric===id);return <button key={id} className={'metric-card '+(fact?.metric===id?'chosen':'')} onClick={()=>f&&chooseFact(f.id)}><span className="metric-label">{metricNames[i]}<ArrowUpRight size={16}/></span><strong>{money(f?.value)}</strong><div className={'metric-rate '+changeTone(c)}>{changeText(c)}<span>{c?.value!=null?'同比':c?.change!=null?'金额变化':'数据不足'}</span></div><div className="metric-foot"><span>{year-1} 年 {money(p?.value)}</span><i className={f?.status==='verified'?'green-dot':'gray-dot'}/></div></button>})}</div>
          <section className="panel memo-panel">{memo?<MemoView run={run} onDiscuss={discuss} onDeepResearch={()=>discuss('请联网多轮检索当前公司，结合年报、最新经营、具体产品和竞争，审视已有估值情景，生成并保存完整投资研究备忘录。')}/>:<div className="empty-inline"><FileSearch/><p>{busy?'正在核对资料，完成后生成研究摘要。':'当前未能形成研究底稿，请查看缺口或重新研究。'}</p></div>}</section>
          <section className="panel"><div className="panel-heading"><h2>年度对照</h2><span className="legend"><i/>{year-1}<i className="current"/>{year}</span></div><div className="comparison-bars">{metricIds.map((id,i)=>{const a=facts.find((f:any)=>f.metric===id&&f.year===year-1)?.value,b=facts.find((f:any)=>f.metric===id&&f.year===year)?.value,max=Math.max(Math.abs(Number(a)||0),Math.abs(Number(b)||0),1);return <div className="bar-row" key={id}><label>{metricNames[i]}</label><div className="bar-pair"><div>{a!=null&&<i style={{width:(Math.abs(Number(a))/max*75)+'%'}}/>}<span>{money(a)}</span></div><div>{b!=null&&<i className="current" style={{width:(Math.abs(Number(b))/max*75)+'%'}}/>}<span>{money(b)}</span></div></div></div>})}</div><div className="panel-footnote">各指标独立缩放，条长表示金额绝对值；正负以标签为准。缺失值以 — 表示。</div></section>
          {!!run.research_snippets?.length&&<section className="panel gap-panel"><div className="panel-heading"><h2><FileSearch size={17}/>补充证据检索</h2><Badge>{run.research_snippets.length} 个原文片段</Badge></div><p className="pad small-muted">根据研究问题检索当前材料。命中关键词不代表片段已解释财务变化。</p>{run.research_snippets.map((s:any,i:number)=><details key={i}><summary>{s.query} · 原文第 {s.page} 页</summary><p className="snippet-text">{s.text}</p><button className="text-link" onClick={()=>setPage({id:s.document_id,page:s.page})}>查看原始页<ArrowUpRight size={13}/></button></details>)}</section>}
          <section className="panel gap-panel"><details><summary>数据完整性 · {run.gaps.length} 项待核实</summary>{run.gaps.map((g:any)=><p key={g.code}>{g.message}</p>)}{!run.gaps.length&&<p>当前没有待补充的数据项。</p>}</details></section>
          <section className="panel"><details className="activity-details"><summary><Activity size={17}/>运行记录 <span>{run.events.length} 个步骤 · {status(run)}</span></summary><EventList run={run}/></details></section>
        </main><aside id="research-evidence" className="evidence-pane" hidden={!showEvidence}><div className="evidence-heading"><span><FileSearch size={18}/>财务来源</span><button className="icon-button" aria-label="关闭财务来源" title="关闭财务来源" onClick={()=>setShowEvidence(false)}><X size={17}/></button></div>{fact?<><div className="evidence-focus"><span>{fact.label} · {fact.year}</span><strong>{money(fact.value)}<small>亿元</small></strong><Badge tone={fact.status==='verified'?'green':fact.status==='conflict'?'red':'amber'}>{({verified:'双源核对一致',conflict:'来源冲突',document_only:'披露文件取值',api_only:'仅结构化来源'} as any)[fact.status]}</Badge></div><div className="source-switch">{sources.map((s:any)=><button key={s.id} className={source?.id===s.id?'selected':''} onClick={()=>setSourceId(s.id)}>{s.kind==='document'?<FileText size={13}/>:<Database size={13}/>} {s.kind==='document'?'原始披露':s.id.startsWith('eastmoney')?'公开财务':'Tushare'}</button>)}</div>{source&&<div className="evidence-content"><span className="tiny-heading">来源材料</span><h3>{source.title}</h3><p className="small-muted">{source.locator}</p><div className="quote">{source.kind==='api'?<details className="evidence-raw"><summary>查看接口原始响应</summary><pre>{formatQuote(source.quote)}</pre></details>:source.quote}</div>{source.kind==='document'&&<button className="page-preview" onClick={()=>setPage({id:source.document_id,page:source.page})}><img src={'/api/documents/'+source.document_id+'/pages/'+source.page} alt={'财务表原文第 '+source.page+' 页'}/><span><Search size={14}/>查看原始第 {source.page} 页</span></button>}<dl className="evidence-meta"><dt>报告口径</dt><dd>年度 · 合并 · 人民币</dd><dt>原始值</dt><dd>{Number(source.kind==='api'?(fact.cross_check_value??fact.value):fact.original_value.replaceAll(',','')).toLocaleString()} {source.kind==='api'?'元':fact.original_unit}</dd><dt>披露日期</dt><dd>{source.announced_date}</dd></dl>{source.source_url&&<a className="text-link" href={source.source_url} target="_blank" rel="noreferrer">打开来源<ExternalLink size={13}/></a>}{source.sha256&&<p className="hash">文件指纹 {source.sha256.slice(0,18)}…</p>}</div>}{calculation&&<div className="formula-box"><span className="tiny-heading">计算过程</span><p>{calculation.formula}</p>{calculation.value!=null&&<code>({calculation.inputs.map((id:string)=>facts.find((f:any)=>f.id===id)?.value).join(' ÷ ')} − 1) × 100</code>}<strong>{calculation.value==null&&calculation.change!=null?'金额变化 ':''}{changeText(calculation)}</strong><small>{calculation.reason||'原始金额统一为元后计算，展示值四舍五入。'}</small></div>}</>:<div className="empty-inline"><FileSearch/><p>选择一项财务数据<br/>查看它的原始来源</p></div>}</aside></div>}
        {tab==='model'&&run&&<ValuationLab key={run.id} run={run} onUpdated={updated} onDiscuss={discuss}/>}
        {tab==='audit'&&run&&<div className="content-page"><div className="section-heading"><div><span className="eyebrow">FACT CHECK</span><h2>在交付之前，再核对一次</h2></div><Badge>{run.checks.filter((c:any)=>c.passed).length} 项程序检查通过</Badge></div><div className="audit-grid"><section className="panel audit-input"><div className="panel-heading"><h2>研究文字核查</h2><FileSearch size={18}/></div><p className="small-muted">与当前研究的本期三项财务事实比较。用于捕捉金额、单位、现金流方向及部分大小关系错误。</p><textarea aria-label="待核查的研究文字" placeholder="粘贴需要核查的研究段落…" value={reviewText} onChange={e=>setReviewText(e.target.value)}/><div className="button-row"><button className="text-button" onClick={()=>setReviewText('美的2025年营业收入4585.02亿元，归母净利润412.67亿元，经营现金流同比增长11.84%，因此盈利质量全面改善。')}>填入美的故意错误示例</button><button className="primary" disabled={!reviewText.trim()||busy} onClick={checkText}><ShieldCheck size={16}/>核查文字</button></div>{review&&<div className="review-result"><h3>{review.issues.length?'发现 '+review.issues.length+' 处需检查内容':'未命中已实现的核查规则'}</h3>{review.issues.map((i:any,n:number)=><div className="audit-issue" key={n}><AlertCircle size={17}/><div><strong>{i.claim}</strong><p>{i.message}</p>{i.expected_100m&&<button className="text-link" onClick={()=>{chooseFact(i.fact_id);setTab('overview')}}>核验值 {Number(i.expected_100m).toFixed(2)} 亿元<ArrowRight size={13}/></button>}</div></div>)}<p className="small-muted">{review.scope}</p></div>}</section><section className="panel checklist"><div className="panel-heading"><h2>本次核验记录</h2><ShieldCheck size={18}/></div>{run.checks.map((c:any,i:number)=><div className="check-row" key={i}>{c.passed?<CheckCircle2 size={17}/>:<AlertCircle size={17}/>}<div><strong>{c.label}</strong><p>{c.detail}</p></div></div>)}{!run.checks.length&&<p className="pad small-muted">研究结束后展示检查记录。</p>}</section></div></div>}
        {tab==='history'&&run&&<div className="content-page"><section className="panel memo-revisions"><div className="panel-heading"><h2>报告修订记录</h2><Badge>当前第 {run.report_revision||1} 版</Badge></div><p className="pad small-muted">在研究对话中提出“更新报告”，新稿会替换当前报告，旧稿保存在这里。</p>{[...(run.memo_revisions||[])].reverse().map((v:any)=><details key={v.revision}><summary>第 {v.revision} 版 → 第 {v.revision+1} 版 · {v.change_note} <small>{when(v.replaced_at)}</small></summary><MemoView run={{...run,memo:v.memo,report_revision:v.revision,report_valuation_status:undefined}}/></details>)}</section></div>}
        {tab==='history'&&run&&<div className="content-page"><div className="section-heading"><div><span className="eyebrow">RESEARCH HISTORY</span><h2>让每次研究都有迹可循</h2></div><button className="secondary" disabled={busy} onClick={()=>act('/runs/'+run.id+'/retry')}><History size={16}/>按原输入重新研究</button></div><section className="panel version-panel"><label>与哪个历史版本比较？<select value={compareId} onChange={e=>{setCompareId(e.target.value);if(e.target.value)api('/runs/'+run.id+'/compare/'+e.target.value).then(setComparison).catch(e=>setError(e.message));else setComparison(null)}}><option value="">选择同公司的历史研究</option>{runs.filter(r=>r.id!==run.id&&r.request.ticker===run.request.ticker).map(r=><option key={r.id} value={r.id}>{when(r.created_at)} · {r.request.mode==='sample'?'样例':'实时'} · {r.id.slice(0,6)}</option>)}</select></label>{comparison&&<div className="version-diff"><h3>{comparison.changes.length?'有 '+comparison.changes.length+' 项数据或核验状态变化':'两版保存的核心财务事实一致'}</h3><p>{comparison.memo_changed?'研究草稿内容有变化，需复核其依据。':'研究草稿内容未变化。'}{comparison.note}</p>{comparison.changes.map((c:any)=><div className="diff-row" key={c.id}><strong>{c.after?.label||c.before?.label} {c.after?.year||c.before?.year}</strong><span>{money(c.before?.value)} → {money(c.after?.value)} 亿元</span><small>{factStatus[c.before?.status]||'无'} → {factStatus[c.after?.status]||'无'}</small></div>)}</div>}</section><section className="panel history-table"><table><thead><tr><th>研究对象</th><th>创建时间</th><th>模式</th><th>状态</th><th/></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td><strong>{r.company}</strong><small>{r.request.ticker} · {r.request.year}</small></td><td>{when(r.created_at)}</td><td>{r.request.mode==='sample'?'样例回放':'实时研究'}</td><td>{status(r)}</td><td><div className="button-row"><button className="text-link" onClick={()=>selectRun(r.id)}>查看<ArrowRight size={13}/></button><button className="text-link" aria-label={"删除研究 "+r.company+" "+r.id.slice(0,6)} disabled={["queued","running"].includes(r.state)} onClick={()=>removeRun(r.id)}><Trash2 size={14}/>删除</button></div></td></tr>)}</tbody></table></section></div>}
        {tab==='library'&&<div className="content-page"><div className="section-heading"><div><span className="eyebrow">SOURCE LIBRARY</span><h1>资料库</h1><p className="small-muted">把研究材料和证券、年度、披露日期绑定，保留原始文件。</p></div></div><section className="panel upload-panel"><div><h2><Upload size={18}/>导入年度报告 PDF</h2><p className="small-muted">支持文本 PDF 全文查阅，最多 100 MB / 800 页。扫描页可用本机 OCR 查阅；财务数值需核对原图。上传后可接入当前研究对话。</p></div><div className="upload-fields"><label>证券代码<input value={uploadMeta.ticker} onChange={e=>setUploadMeta({...uploadMeta,ticker:e.target.value.toUpperCase()})}/></label><label>报告年度<input type="number" value={uploadMeta.year} onChange={e=>setUploadMeta({...uploadMeta,year:Number(e.target.value)})}/></label><label>公告日期<input type="date" value={uploadMeta.announced_date} onChange={e=>setUploadMeta({...uploadMeta,announced_date:e.target.value})}/></label><button className="primary" disabled={uploading} onClick={()=>fileInput.current?.click()}>{uploading?<LoaderCircle className="spin" size={16}/>:<Upload size={16}/>}选择 PDF</button><input hidden type="file" accept=".pdf,application/pdf" ref={fileInput} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></div></section><div className="document-grid">{docs.map(d=><section className="panel document-card" key={d.id}><span className="document-icon"><FileText size={25}/></span><Badge>{d.kind==='official_sample'?'官方样例':d.kind==='public_report'?'公开年报':'本地材料'}</Badge><h3>{d.title}</h3><p>{d.ticker} · {d.year} 年</p><small>公告日期 {d.announced_date||'未确认'} · {d.page_count?d.page_count+' 页':'可查阅'}</small><div><a className="text-link" href={'/api/documents/'+d.id+'/file'} target="_blank" rel="noreferrer">打开原文<ExternalLink size={13}/></a><button className="text-link" onClick={()=>{setForm({...form,ticker:d.ticker,year:d.year,document_id:d.id,mode:'live'});setShowNew(true)}}>用于新研究<ArrowRight size={13}/></button>{run&&d.ticker===run.request.ticker&&d.year===run.request.year&&<button className="text-link" disabled={busy} onClick={()=>attachExisting(d)}>接入当前对话<ArrowRight size={13}/></button>}</div></section>)}</div></div>}
        {tab==='trash'&&<HistoryTrash onRestored={refreshRuns}/>}
        {tab==='settings'&&<ConnectionSettings config={config} onChange={setConfig}/>}
      </>}
      </>}
    </div>
    {showNew&&<Modal title="开始一份新研究" onClose={()=>setShowNew(false)}><form onSubmit={e=>{e.preventDefault();start()}}>
      <div className="mode-options"><button type="button" className={form.mode==='live'?'selected':''} onClick={()=>setForm({...form,mode:'live'})}><Sparkles size={20}/><strong>实时研究</strong><span>选择数据源 · 模型分析</span></button><button type="button" className={form.mode==='sample'?'selected':''} onClick={()=>setForm({...form,mode:'sample',ticker:'000333.SZ',year:2025,document_id:''})}><BookOpen size={20}/><strong>样例回放</strong><span>美的 2025 · 已保存快照</span></button></div>
      <CompanySearch value={form.ticker} disabled={form.mode==='sample'} onChange={(ticker:string)=>setForm((f:any)=>({...f,ticker,document_id:''}))}/>
      <div className="form-row"><label>报告年度<input required type="number" min="2000" max={new Date().getFullYear()} value={form.year} disabled={form.mode==='sample'} onChange={e=>setForm({...form,year:Number(e.target.value),document_id:''})}/></label><label>研究截止日<input required type="date" max={config.today} value={form.as_of} onChange={e=>setForm({...form,as_of:e.target.value})}/></label></div>
      {form.mode==='live'&&<label>本次数据源<select value={form.data_source||'default'} onChange={e=>setForm({...form,data_source:e.target.value})}><option value="default">使用默认 · {config.data_sources?.find((s:any)=>s.id===config.data_source)?.name}</option>{config.data_sources?.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}
      <label>研究问题<textarea required minLength={4} maxLength={1500} rows={3} value={form.question} onChange={e=>setForm({...form,question:e.target.value})}/></label><label>参考材料<select value={form.document_id||''} onChange={e=>setForm({...form,document_id:e.target.value})}><option value="">自动匹配内置材料 / 仅结构化数据</option>{docs.filter(d=>d.ticker===form.ticker&&d.year===Number(form.year)).map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label>{form.mode==='live'&&<label className="checkbox-label"><input type="checkbox" checked={form.use_model} onChange={e=>setForm({...form,use_model:e.target.checked})}/>调用模型提出研究追问并生成草稿</label>}<div className="modal-note">{form.mode==='sample'?'样例使用 2026-09-28 保存的数据，不调用实时接口或模型。':'完成财务底稿后，可以在研究对话中继续讨论、估值或修订报告。'}</div>{error&&<p className="form-error">{error}</p>}<button className="primary full" disabled={creating||!form.ticker} type="submit">{creating?<LoaderCircle size={17} className="spin"/>:<ArrowRight size={17}/>}开始研究</button></form></Modal>}
    {showExport&&run&&<Modal title="导出报告与审计材料" onClose={()=>setShowExport(false)}><p className="small-muted">当前报告便于阅读和编辑；完整审计材料保留全部修订历史。独立报告中的本地 PDF 链接需本机服务，交给他人请用证据包。</p><div className="export-options">{[['markdown','当前报告 · Markdown','当前稿、来源与最新保存的估值假设'],['html','当前报告 · 可打印版','浏览器阅读、打印或保存 PDF'],['audit-markdown','完整审计底稿','全部修订历史、计算及运行记录'],['json','完整结构化记录','保留原始 JSON 与全部历史版本'],['bundle','完整证据包 · ZIP','离线报告、已存 PDF、文件指纹及联网来源清单']].map(([format,title,desc])=><a key={format} href={'/api/runs/'+run.id+'/export?format='+format+(format==='html'?'&preview=true':'')} target={format==='html'?'_blank':undefined} rel={format==='html'?'noreferrer':undefined}><FileText size={22}/><div><strong>{title}</strong><small>{desc}</small></div><ArrowDownToLine size={18}/></a>)}</div></Modal>}
    {page&&<Modal title={'披露文件 · 第 '+page.page+' 页'} wide onClose={()=>setPage(null)}><div className="source-modal-actions"><a className="text-link" href={'/api/documents/'+page.id+'/file#page='+page.page} target="_blank" rel="noreferrer">打开完整 PDF<ExternalLink size={14}/></a></div><img className="full-page-image" src={'/api/documents/'+page.id+'/pages/'+page.page} alt={'原始披露文件第'+page.page+'页'}/></Modal>}
  </div>
}
function formatQuote(value:string){try{return JSON.stringify(JSON.parse(value),null,2)}catch{return value}}
function EventList({run}:any){return <div className="events">{run.events.map((e:any,i:number)=><div className="event" key={i}><CheckCircle2 size={14}/><time>{when(e.time)}</time><div><strong>{e.label}</strong><p>{e.detail}</p></div></div>)}</div>}
